In [1]:
import numpy as np

In [2]:
arr= np.array([[1 ,2 ,3],
               [4 ,4, 5]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

2

In [5]:
arr.shape

(2, 3)

In [6]:
import numpy as np

# creating array object
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])

# printing type of arr object
print("Array is of type: ", type(arr))

# printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# printing shape of array
print("Shape of array: ", arr.shape)

# printing size (total number of elements) of array
print("Size of array: ", arr.size)

# printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [10]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)


b = np.array((1 , 3, 2))
print("\nArray created using passed tuple:\n", b)

c = np.zeros((3, 4))
print("\nAn array initialized with all zeros:\n", c)


e = np.random.random((2,2))
print("\nA random array:\n", e)

g = np.linspace(0, 5, 10)
print("\nA sequential array with 10 values between 0 and 5:\n", g)




arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)



Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

A random array:
 [[0.81852832 0.90730312]
 [0.23204138 0.95226105]]

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [11]:
a = np.array([1, 2, 5, 3])

# add 1 to every element
print("Adding 1 to every element:", a+1)

# subtract 3 from each element
print("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print("Multiplying each element by 10:", a*10)

# square each element
print("Squaring each element:", a**2)

# modify existing array
a *= 2
print("Doubled each element of original array:", a)

# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
